### ISSUE TITLE
3월18일 영서의 일기

### ISSUE THREAD

**Issue by kys6879** [xjobs1068/C_language#4]
오늘은 월요일이다. 주말에 놀고 오랜만에 출근을 하려니 몸이 뻐근하다.
그래도 어찌하겠는가, 돈을 벌어야 한다.
찌뿌둥한 몸을 이끌고 회사를 갔다 . 
회사에서 금요일 날 하고 갔던 코드를 조금 더 수정하고
angular 학습에 들어갔다. 
퇴근을 하고 집에와서 파스타를 먹었다.
참 재밌는 하루였다. 모두 파이팅!!

**Comment by oocjh2000** [comment]
김 선생님의 하루를 엿보니 저도 갓개발자가 된 거 같습니다.
저도 김 선생님을 본받아 더욱 정진하겠습니다.
