### ISSUE TITLE
(중요) 저장소 기여 가이드라인 안내

### ISSUE THREAD

**Issue by getsolaris** [xjobs1068/C_language#5]
안녕하세요.
:kr: 저희 선생님을 지지하는 김민근입니다.

:sound: :sound: :sound: :sound:

2019-03-18 자로 해당 저장소 공식 가이드라인이 완성 되었습니다. :open_file_folder:
가이드라인을 안내해드리겠습니다.

## 저장소 안내
해당 저장소는 저희 선생님(이현찬)께서 국립 공주대학교 CSE 에서 배운 내용을 복습 하는 차원으로
생성된 저장소입니다.

## 기여 하실분들은 해당 저장소를 Fork 해가신다음 수정 후 PR을 넣습니다.
1. :clock11: 23시 부터 08시 까지는 PR 금지! :x:
- 이유: 이현찬선생님이 주무실때 알림이 가지 않도록 조심합니다. 
2. 소스코드를 첨부하여 PR 시 주석은 꼭 달도록 합니다.
- 이유: 이현찬선생님께서는 그냥 보면 이해를 못해 주석을 꼭 달아드려야 합니다. :100:
3. PR 제목은 명확하게 제공을 해야 저희 선생님께서 보기 편하십니다.
4. PR 제목 및 내용, 주석에는 영어를 적으시면 안됩니다.
- 이유: 선생님께서는 영어 울렁증을 앓고 계십니다. :see_no_evil:
5. 칭찬은 돌고래도 춤추게 합니다.
- 저희 선생님이 개발을 이상하게 하더라도 칭찬을 해주세요. :100:

## 이슈 안내
이슈는 기여자들의 일기를 업로드 해도 무관하고, 개인적으로 선생님께 드리고 싶은 내용을 생성해도 됩니다.
이슈게시판은 일반 커뮤니티라고 생각하시어 자유롭게 생성해주시면 됩니다. :smiley: :smiley:

지속적으로 기여를해 저희 선생님 눈에(:eyes:) 들어오면 이쁨을 받으실 수 있습니다.

해당 가이드라인을 참고해 모두 저희 선생님에게 이쁨을 받아봅시다 !

읽어주셔서 감사합니다.

**Comment by kys6879** [comment]
좋은 가이드라인 선사 감사드립니다. 덕분에 PR 를 하기에 훨씬 수월해지고 , 틀이 생겨 더욱 견고한 PR 을 날릴 수 있을 것 같습니다. 수고하셨습니다.

**Comment by getsolaris** [comment]
저희 선생님 담당 스태프입니다. 궁금하신점 있으시면 mention 주시면 되겠습니다.

김영서(@kys6879) 차재훈(@oocjh2000)

**Comment by oocjh2000** [comment]
케빈선생님 덕분에 더욱 좋은 오픈소스 문화가 만들어지는거 같습니다.
앞으로도 많은 활동 부탁드리겠습니다.
