### ISSUE TITLE
Day3는 언제올라올까요?

### ISSUE THREAD

**Issue by oocjh2000** [xjobs1068/C_language#7]
평소 이현찬 개발자님의 코드를 보며 프로그래밍을 공부하는 학생입니다.
어제 선생님의 코드를 접하고 프로그래밍에 입문하게 되었습니다.
오늘 2일 차로서 선생님께서 짜신 완벽한 학습자료가 바닥이 났습니다.
3일 차 학습자료가 언제 올라올지 귀띔해 주신다면 매우 감사하겠습니다

**Comment by kys6879** [comment]
저도 매우 기대되는 사항입니다. watch를 키고 하루사철 장마철 이기철 이현찬개발자님의 저장소를 새로고침하며 뼈가빠지도록 기다리고 있습니다. 새롭고 , 긍정적인 소식 기다리겠습니다.
