### ISSUE TITLE
오늘 점심식사 추천 받아요.

### ISSUE THREAD

**Issue by getsolaris** [xjobs1068/C_language#9]
👍 오늘 점심은 뭐가 좋을까요 ?

**Comment by oocjh2000** [comment]
공주대 학식 추천드립니다

**Comment by getsolaris** [comment]
> 공주대 학식 추천드립니다

감사합니다.
역시 저희 선생님께서 재학중인 학교에서 점심을 먹는다는건 현명한 판단이신것 같습니다.

**Comment by kys6879** [comment]
서브웨이는 어떠신가요? 저는 평소에 야채없이 서브웨이 샌드위치를 즐겨먹곤합니다.

**Comment by getsolaris** [comment]
> 서브웨이는 어떠신가요? 저는 평소에 야채없이 서브웨이 샌드위치를 즐겨먹곤합니다.

서브웨이 추천 감사드립니다.
공주대 앞에 위치해있는 `서브웨이 공주대신관점` 에서 야채빼고 먹어보겠습니다.
